SELECT MEMBRE.NOM ,COUNT(MEMBRE.NOM) AS "NB AMIS" FROM MEMBRE,RELATION_USER WHERE RELATION_USER.MEMBRE1 = MEMBRE.ID AND RELATION_USER.STATUT = 1 GROUP BY MEMBRE.NOM;

SELECT NOM , (SELECT COUNT(ID) FROM RELATION_USER WHERE STATUT = 1 AND MEMBRE1 = MEMBRE.id)/((SELECT COUNT(ID) FROM RELATION_USER WHERE STATUT = 2 AND MEMBRE1 = MEMBRE.ID)+(SELECT COUNT(ID) FROM RELATION_USER WHERE STATUT = 1 AND MEMBRE1 = MEMBRE.ID))*100 AS "%" FROM MEMBRE;

SELECT COUNT(ID) FROM LIKE_PAGE WHERE PAGE = 0 GROUP BY ID;

SELECT COUNT(VILLE_RESIDENCE) AS "IN PARIS" FROM MEMBRE WHERE VILLE_RESIDENCE IN (SELECT ID FROM VILLE WHERE DEPARTEMENT = 75) AND ID IN (SELECT MEMBRE FROM LIKE_PAGE WHERE PAGE = 1) AND ((TO_DATE(SYSDATE,'dd-mm-YY') - DATE_NAISSANCE) / 365) BETWEEN 18 AND 25 GROUP BY VILLE_RESIDENCE;

SELECT EVENEMENT FROM ADMINISTRATEUR_EVENEMENT WHERE MEMBRE = 3 AND  (SELECT COUNT(STATUT) FROM PARTICIPANT WHERE STATUT = 2 AND PARTICIPANT.EVENEMENT = ADMINISTRATEUR_EVENEMENT.EVENEMENT GROUP BY STATUT) > (SELECT COUNT(STATUT) FROM PARTICIPANT WHERE STATUT = 1 AND PARTICIPANT.EVENEMENT = ADMINISTRATEUR_EVENEMENT.EVENEMENT GROUP BY STATUT);

SELECT COUNT(COUNT(MEMBRE)) FROM PARTICIPANT WHERE STATUT = 1 AND MEMBRE IN (SELECT ID FROM MEMBRE WHERE VILLE_RESIDENCE IN (SELECT ID FROM VILLE WHERE DEPARTEMENT = 75))  GROUP BY MEMBRE;

SELECT ( SELECT SUM(((TO_DATE(SYSDATE,'dd-mm-YY') - DATE_NAISSANCE) / 365)) FROM MEMBRE WHERE ID IN (SELECT ID FROM LIKE_PAGE WHERE PAGE = 1) )/(SELECT COUNT(COUNT(ID)) FROM MEMBRE WHERE ID IN (SELECT ID FROM LIKE_PAGE WHERE PAGE = 1)  GROUP BY ID ) FROM MEMBRE WHERE id = 0;

SELECT NOM FROM MEMBRE WHERE VILLE_RESIDENCE = VILLE_NAISSANCE;

SELECT ((TO_DATE(SYSDATE,'dd-mm-YY') - DATE_NAISSANCE) / 365) AS AGE FROM MEMBRE WHERE ((TO_DATE(SYSDATE,'dd-mm-YY') - DATE_NAISSANCE) / 365) = (SELECT MAX((TO_DATE(SYSDATE,'dd-mm-YY') - DATE_NAISSANCE) / 365) FROM MEMBRE) ;

SELECT * FROM(SELECT NOM FROM MEMBRE GROUP BY NOM  ORDER BY COUNT(ID) DESC ) WHERE ROWNUM < 2 ;

SELECT NOM FROM MEMBRE WHERE ID IN  (SELECT MAX(COUNT(MEMBRE)) FROM IDENTIFIE GROUP BY ID);

SELECT NOM FROM MEMBRE WHERE ID IN (SELECT MEMBRE FROM LIKE_PAGE WHERE DATE_LIKE BETWEEN TO_DATE('2021-01-17','YYYY-mm-dd') AND TO_DATE('2021-01-23','YYYY-mm-dd'));




