SELECT NOM , CAPACITE FROM AVION WHERE CAPACITE > 200 AND CAPACITE < 300 ORDER BY CAPACITE ASC ;

SELECT NOM , LARGEUR , LARGEUR/100 FROM AVION;

SELECT COUNT(NOM)  FROM AVION  WHERE CAPACITE > 400;

SELECT COUNT(ID) FROM PASSAGER WHERE POIDS > 80 AND POIDS < 90 ;
SELECT NOM, PRENOM FROM PASSAGER WHERE POIDS > 80 AND POIDS < 90;

ALTER TABLE AVION MODIFY NOMBRE_REACTEURS INTEGER CHECK(NOMBRE_REACTEURS > 0);

SELECT SUM(POIDS) FROM PASSAGER WHERE VOL = 130;

INSERT INTO VOL(ID, DESIGNATION, VILLE_ORIGINE, VILLE_ARRIVEE, AVION, DATE_DEPART) VALUES ((SELECT max(ID)  +1 FROM VOL),'trajet speciale',(SELECT CODE_POSTAL FROM VILLE WHERE NOM = 'Bilbo'),(SELECT CODE_POSTAL FROM VILLE WHERE NOM = 'Wanaka'), 169,'2023-03-17');

SELECT DESIGNATION, DATE_DEPART,NOM FROM VOL,AVION WHERE VOL.AVION = AVION.IMMATRICULATION;

SELECT DESIGNATION, VILLE_ORIGINE , VILLE_ORIGINE, CAPACITE FROM VOL , AVION WHERE AVION.CAPACITE > 150 AND AVION.CAPACITE < 200;

UPDATE VOL SET DATE_ARRIVEE = DATE_DEPART + DUREE WHERE DATE_ARRIVEE IS NULL;

SELECT COUNT(ID) FROM PASSAGER GROUP BY VOL;

SELECT MAX(COUNT(ID)) FROM PASSAGER GROUP BY VOL;

SELECT SUM(POIDS) FROM PASSAGER GROUP BY VOL;