SELECT NOM,PRENOM FROM PERSONNE WHERE LENGTH(NOM) >= 5;

SELECT NOM,PRENOM FROM PERSONNE WHERE MOD(LENGTH(NOM) + LENGTH(PRENOM),7) = 0;

SELECT NOM,PRENOM FROM PERSONNE WHERE LENGTH(NOM) = (SELECT MAX(LENGTH(NOM)) FROM PERSONNE) ;

SELECT COUNT(NOM) FROM PERSONNE WHERE INSTR(VILLE,' ') != 0 OR INSTR(VILLE,'-') != 0;

SELECT SUBSTR(MAIL,INSTR(MAIL,'@')+1) FROM PERSONNE;

SELECT NOM,PRENOM,ADRESSE FROM  PERSONNE WHERE ADRESSE LIKE '%Rd.%';

UPDATE PERSONNE SET ADRESSE = CONCAT(SUBSTR(ADRESSE,0,INSTR(ADRESSE,'Rd.')-1),'Road.') WHERE ADRESSE LIKE '%Rd.%';

SELECT NOM,PRENOM,ADRESSE FROM  PERSONNE WHERE ADRESSE LIKE '%Road.%';

ALTER TABLE PERSONNE ADD SEXE CHAR(1);

UPDATE PERSONNE SET SEXE = 'F' WHERE SUBSTR(PRENOM,LENGTH(PRENOM)) = 'a' OR SUBSTR(PRENOM,LENGTH(PRENOM)) = 'e' OR SUBSTR(PRENOM,LENGTH(PRENOM)) = 'i' OR SUBSTR(PRENOM,LENGTH(PRENOM)) = 'o' OR SUBSTR(PRENOM,LENGTH(PRENOM)) = 'u';

UPDATE PERSONNE SET SEXE = 'H' WHERE SEXE IS NULL ;

ALTER TABLE PERSONNE ADD INITIALE CHAR(3);

UPDATE PERSONNE SET INITIALE = CONCAT(CONCAT(SUBSTR(NOM,0,1),'.'),SUBSTR(PRENOM,0,1));

ALTER TABLE PERSONNE ADD MAIL2 VARCHAR(200);

UPDATE PERSONNE SET MAIL2 = CONCAT(CONCAT(CONCAT(LOWER(PRENOM),'.'),LOWER(NOM)),'@esgi.fr');